version: '3'
services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      - POSTGRESQL_URL=postgresql://zebrands:zebrands@postgres:5432/zebrands
      - SECRET_KEY=d3qrf3vt43.rf43tv43tgv43c346v4g5454h4vbh.hbv4h54vhc54hv54h54ch54
      - MAIL_USERNAME=example@gmail.com
      - MAIL_PASSWORD=password
      - MAIL_FROM=example@gmail.com
      - MAIL_PORT=587
      - MAIL_SERVER=smtp.gmail.com
      - MAIL_TLS=True
      - MAIL_SSL=False
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: zebrands
      POSTGRES_PASSWORD: zebrands
      POSTGRES_DB: zebrands
    ports:
      - "5432:5432"
