"""first migration

Revision ID: 3bb35615b9bf
Revises: 
Create Date: 2023-11-30 14:52:16.255376

"""

# revision identifiers, used by Alembic.
revision = "3bb35615b9bf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
