name: CI/CD
on:
  push:
    branches: [ "main" ]
jobs:
  Test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: zebrands
          POSTGRES_PASSWORD: zebrands
          POSTGRES_DB: zebrands
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      OS: ubuntu-latest
      PYTHON: '3.12'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.12"
      - name: 'Run Tests'
        env:
          POSTGRESQL_URL: postgresql://zebrands:zebrands@localhost:5432/zebrands
          SECRET_KEY: helloiamsecretkeyfortest
          MAIL_USERNAME: arianventura94@gmail.com
          MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
          MAIL_FROM: arianventura94@gmail.com
          MAIL_PORT: 587
          MAIL_SERVER: smtp.gmail.com
          MAIL_TLS: true
          MAIL_SSL: false
        run: |
          python -m pip install --upgrade pip          
          pip install poetry pytest httpx factory-boy
          poetry export -f requirements.txt --output requirements.txt --without-hashes 
          pip install -r requirements.txt
          python -m pytest
  Docker:
    runs-on: ubuntu-latest
    needs: Test
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
          docker build . --file Dockerfile -t v3n2r4/zebrands_test:latest -t v3n2r4/zebrands_test:$(echo $GITHUB_SHA | head -c7)          
          docker push v3n2r4/zebrands_test:latest
          docker push v3n2r4/zebrands_test:$(echo $GITHUB_SHA | head -c7)
  Deploy:
    runs-on: ubuntu-latest
    needs: Docker
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save DigitalOcean kubeconfig with short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 zebrands-services
      - name: Deploy to DigitalOcean Kubernetes
        run: kubectl --namespace=zebrands-services set image deployment.v1.apps/zebrands-services container-zebrands-services=v3n2r4/zebrands_test:$(echo $GITHUB_SHA | head -c7)
      - name: Verify deployment
        run: kubectl --namespace=zebrands-services rollout status deployment/zebrands-services