name: Test
on:
  push:
    branches-ignore: [ "main"]
jobs:
  Test:
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      PYTHON: '3.12'
    steps:
      - uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: "3.12"
      - name: 'Run Tests'
        run: |
          python -m pip install --upgrade pip          
          pip install poetry pytest httpx factory-boy
          poetry export -f requirements.txt --output requirements.txt --without-hashes 
          pip install -r requirements.txt
          python -m pytest
